website/__init__.py
from flask import Flask
from sys import exit

from website.examples import Examples

def create_app() -> Flask:
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'ALKJHSFEGONEPNoingboajnfd65487'

    from .views import Views
    from .auth import Auth
    from .examples import Examples

    app.register_blueprint(Views, url_prefix="/")
    app.register_blueprint(Auth, url_prefix='/auth')
    app.register_blueprint(Examples, url_prefix='/examples')

    return app


if __name__ == "__main__":
    exit()

website/auth.py
from flask import Blueprint, render_template, request

Auth = Blueprint('Auth', __name__)

@Auth.route('/login', methods=['GET'])
def render_login() -> str:
    return render_template('user_input_tmp.html', type="Login")


@Auth.route('/login', methods=['POST'])
def login():
    pass

@Auth.route('/logout')
def logout() -> str:
    content: str = """
Could not find the page you were looking for.
Please make sure your link is valid, and it was typed correctly.
    """
    return render_template('error.html', error_code="404", error_content=content)


@Auth.route('/sign-up', methods=['GET'])
def render_sign_up() -> str:
    return render_template('user_input_tmp.html', type="Sign Up")


@Auth.route('/sign-up', methods=['POST'])
def sign_up() -> str:
    pass

website/views.py
from flask import Blueprint, render_template, request


Views = Blueprint('views', __name__)


@Views.route('/')
def home() -> str:
    return render_template("base.html", title="Homepage", inAuth=False)


@Views.route('/user-page')
def user_page(user_name:str=None) -> str:
    if user_name:
        return render_template("user_home_page.html", user_name=user_name)

    error_content: str = """
As a non-user, you are trying to accese some user content.
Please return to your designated area.
    """

    return render_template("error.html", error_code="505", error_content=error_content)

website/templates/base.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta name="charset" charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="tags" content="Fun Project No-Real">
        <meta name="auther" content="Void, Sai">

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

        <title>Flask Project</title>
    </head>
    <body>
        <h1>{{ title }}</h1>
        <div class="auth">
            {% if inAuth == False %}
            <a href="auth/login">Login</a>
            <a href="auth/logout">Logout</a>
            <a href="auth/sign-up">Sign Up</a>
            {% else %}
            <a href="login">Login</a>
            <a href="logout">Logout</a>
            <a href="sign-up">Sign Up</a>
            <a href="/">To homepage</a>
            {% endif %}
        </div>
    </body>
</html>

website/templates/error.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta name="charset" charset="utf-8">
        <meta name="auther" content="Void, Sai">
        <meta name="tags" content="ERROR">
        <meta name="viewport" content="width=device-width initial-scale=1">

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/error.css') }}">

        <title>ERROR: {{ error_code }}</title>
    </head>
    <body>
        <div class="error-title">
            <h1>{{ error_code }}</h1>
            <h2>You have encounterd an ERROR</h2>
        </div>
        <p class="error-message">
            {{ error_content }}
        </p>
    </body>
</html>

website/templates/examples/block-example.html
{% extends "nav_bar.html" %}
{% block title %}Testing env{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    <p>This is from testing</p>
{% endblock %}

website/templates/examples/form-example.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta name="charset" charset="utf-8">
        <meta name="viewport" content="width=device-width initial-scale=1">
        <title>Form example</title>
    </head>
    <body>
        <h1>Form Example</h1>
        <!-- Remeber that form requres the action and method to work, you dumb idiot self. -->
        <form action="{{ url_for('Examples.form_example') }}" method='post'>
            <input type="text" name="Username" placeholder="Username">
            <input type="submit">
        </form>
        <p>{{ inpt }}</p>
    </body>
</html>

website/templates/examples/search-line-example.html
<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Search line example</title>
	</head>
	<body>
		<h1>Search line example</h1>
		<p>{{ content }}</p>
	</body>
</html>

website/templates/nav_bar.html
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Project | {% block title %}{% endblock %}</title>
    {% endblock %}
</head>
<body>
    <div id="content">{% block content %}{% endblock %}</div>
    <div id="footer">
        {% block footer%}
        <p>This is the footer</p>
        {% endblock %}
    </div>
</body>
</html>

website/templates/testing.html
{% extends "nav_bar.html" %}
{% block title %}Testing env{% endblock %}
{% block head %}
    {{ super() }}
{% endblock %}
{% block content %}
    <p>This is from testing</p>
{% endblock %}

website/templates/user_home_page.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta name="charset" charset="utf-8">
        <meta name="viewport" content="width=device-width initial-scale=1">
        <meta name="tags" content="User Homepage">
        <meta name="auther" content="Void, Sai">

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/user_home_page.css') }}">

        <title>Flask Project | {{ user_name }}'s Page</title>
    </head>
    <body>
        <div class="auth">
            <a href="auth/logout">Logout</a>
        </div>
    </body>
</html>

website/templates/user_input_tmp.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta name="charset" charset="utf-8">
        <meta name="viewport" content="width=device-width initial-scale=1">
        <meta name="auther" content="Void, Sai">
        <meta name="tags" content="Login Sign-Up Project">

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/user_input.css') }}">

        <title>Flask Project | {{ type }}</title>
    </head>
    <head>
        <h1>{{ type }}</h1>
        <div class="input-field">
            {% if type == "Login" %}
            <form action="{{ url_for('Auth.login') }}" method="post">
            {% elif type == "Sign Up" %}
            <form action="{{ url_for('Auth.sign_up') }}" method="post">
            {% endif %}
                <input type="text" name="Username" placeholder="Enter username here">
                <input type="text" name="Password" placeholder="Enter password here">
                <input type="submit" placeholder="Submit">
            </form>
        </div>
        <div class="nav-bar">
            <a href="/">Home Page</a>
        </div>
    </head>
</html>